apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-server
  namespace: nrprediger  # <--- ADICIONE ISSO
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash-server
  template:
    metadata:
      labels:
        app: dash-server
    spec:
      containers:
      - name: dash-server
        image: marcosmagnocarvalho/videoserver:cni
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dash-server-service
  namespace: nrprediger  # <--- ADICIONE ISSO AQUI TAMBÉM
spec:
  selector:
    app: dash-server
  ports:
  - name: http
    port: 8080
    targetPort: 80