apiVersion: v1
kind: ConfigMap
metadata:
  name: dash-config
data:
  # URL Corrigida com o caminho completo que você descobriu
  MPD_URL: "http://dash-server-service:8080/BBB_vod_2s/ftp.itec.aau.at/datasets/DASHDataset2014/BigBuckBunny/2sec/BigBuckBunny_2s_simple_2014_05_09.mpd"
  LOG_LEVEL: "info"
  SESSION_DURATION: "300" 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-clients
  namespace: nrprediger

spec:
  replicas: 1  # Recomendo começar com 1 para testar antes de subir para 20
  selector:
    matchLabels:
      app: dash-client
  template:
    metadata:
      labels:
        app: dash-client
    spec:
      containers:
      - name: dash-client
        image: rambo1802/dash-node:latest  # <--- Mude aqui
        imagePullPolicy: Always
        env:
        - name: MPD_URL
          valueFrom:
            configMapKeyRef:
              name: dash-config
              key: MPD_URL
        - name: SESSION_DURATION
          valueFrom:
            configMapKeyRef:
              name: dash-config
              key: SESSION_DURATION
        resources:
          # O Chrome consome mais RAM, precisamos ajustar os limites
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"