---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: nrprediger
  labels:
    epc-mode: webui
spec:
  selector:
    epc-mode: webui
  ports:
    - name: http2-open5gs-webui-3000
      protocol: TCP
      port: 4000
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: nrprediger
  labels:
    epc-mode: webui
    app: webui
    version: v2.4.11
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
  template:
    metadata:
      labels:
        epc-mode: webui
        app: webui
        version: v2.4.11
    spec:  
      containers:
        - name: webui
          image: maikovisky/open5gs-webui:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun"
          env:
            - name: DB_URI 
              value: "mongodb://mongo/open5gs"
            - name: HOSTNAME
              value: 0.0.0.0
            - name: PORT
              value: "4000"
          command: ["npm", "run", "dev"]
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---