apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-deletion-script
  namespace: nrprediger
data:
  delete-subscribers.js: |
    print("--- CONECTANDO AO BANCO OPEN5GS PARA LIMPEZA ---");
    db = db.getSiblingDB('open5gs');

    // CONFIGURAÇÃO: Defina o intervalo que deseja apagar
    // Certifique-se que bate com o intervalo usado na criação
    var start_imsi_suffix = 17;
    var end_imsi_suffix = 80;
    var mcc_mnc = "99970";

    var deleted_count = 0;

    for (var i = start_imsi_suffix; i <= end_imsi_suffix; i++) {
        // Lógica de sufixo idêntica ao script de criação (01, 02... 10, 11)
        var suffix = (i < 10 ? "0" + i : i); 
        
        // Constrói o IMSI completo
        var imsi = mcc_mnc + "00000000" + suffix;

        // Executa a remoção
        var result = db.subscribers.remove({ "imsi": imsi });

        if (result.nRemoved > 0) {
            print("[-] IMSI " + imsi + ": DELETADO.");
            deleted_count++;
        } else {
            print("[?] IMSI " + imsi + ": Não encontrado (já foi apagado?).");
        }
    }
    print("------------------------------------------------");
    print("Total de UEs removidas: " + deleted_count);

---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-ues-job
  namespace: nrprediger
spec:
  ttlSecondsAfterFinished: 10 # O Job se auto-destrói 30s após terminar
  template:
    spec:
      containers:
      - name: mongo-client
        image: mongo:4.4
        command: ["mongo"]
        # Conecta no host 'mongo' (padrão do Open5GS no k8s) e roda o script
        args: ["mongodb://mongo:27017/open5gs", "/scripts/delete-subscribers.js"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: ue-deletion-script
      restartPolicy: Never